### ISSUE TITLE
Problems using the liboidc-agent python library

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/liboidc-agent-py#3]
Hi,

There seems to be a problem with the socket protocol:

```
paul@sprocket:~$ oidc-add XDC
Enter encryption password for account config XDC: 
success
paul@sprocket:~$ pip3 install liboidcagent
Collecting liboidcagent
  Using cached https://files.pythonhosted.org/packages/68/f3/147ed2d630cdd6b2ce14c5523c55db75a7e6b3efbbbd8caf174f23965b15/liboidcagent-0.2.1-py3-none-any.whl
Installing collected packages: liboidcagent
Successfully installed liboidcagent-0.2.1
paul@sprocket:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import liboidcagent as agent
>>> agent.get_access_token("XDC")
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.5/site-packages/liboidcagent/liboidcagent.py", line 85, in _communicate_with_sock
    sock.connect(socket_path)
OSError: [Errno 91] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python3.5/site-packages/liboidcagent/liboidcagent.py", line 38, in get_access_token
    scope, audience)[0]
  File "/home/paul/.local/lib/python3.5/site-packages/liboidcagent/liboidcagent.py", line 28, in get_token_response
    application_hint, scope, audience))
  File "/home/paul/.local/lib/python3.5/site-packages/liboidcagent/liboidcagent.py", line 88, in _communicate_with_sock
    'Could not connect to oidc-agent: {}'.format(str(err)))
liboidcagent.liboidcagent.OidcAgentConnectError: Could not connect to oidc-agent: [Errno 91] Protocol wrong type for socket
>>> 
```

**Comment by paulmillar** [comment]
Sorry, I believe this was due to my laptop running an old version of oidc-agent.

**Comment by zachmann** [comment]
> Sorry, I believe this was due to my laptop running an old version of oidc-agent.

This is plausible. The socket type was changed with version 3.0.0 of oidc-agent. Indeed new libraries and clients (this actually includes oidc-add) are incompatible with an agent < 3.0.0

So after an update to version 3 the agent must be restarted. Since version 3.0.0 was released quite some time ago, this is a bit surprising that there was still an old agent running, but not impossible.

**Comment by paulmillar** [comment]
Yes, this problem was fixed by upgrading the version of oidc-agent. 

This has revealed a new problem: #4
