### ISSUE TITLE
Usage of future.standard_library causes warning in python 3.10

### ISSUE THREAD

**Issue by lburgey** [indigo-dc/liboidc-agent-py#9]
Here the warning:
```
.../lib/python3.10/site-packages/future/standard_library/__init__.py:65: 

DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp
```

This is totally not urgent, just a heads up.

**Comment by enolfc** [comment]
This is finally removed in python3.12 and fails, see below using it with fedcloudclient:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/fedcloud", line 5, in <module>
    from fedcloudclient.cli import cli
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/fedcloudclient/cli.py", line 7, in <module>
    from fedcloudclient.checkin import token
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/fedcloudclient/checkin.py", line 12, in <module>
    import liboidcagent as agent
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/liboidcagent/__init__.py", line 3, in <module>
    from .liboidcagent import OidcAgentError, OidcAgentRemoteError, OidcAgentConnectError, OidcAgentCryptError
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/liboidcagent/liboidcagent.py", line 14, in <module>
    from future.standard_library import install_aliases
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by zachmann** [comment]
@enolfc which version of the library do you use?

The `future` import should already be removed since quite a while.

**Comment by enolfc** [comment]
This comes from fedcloudclient, I see there the dependency specified in [requirements.txt](
https://github.com/tdviet/fedcloudclient/blob/master/requirements.txt#L8C20-L8C20):

```
liboidcagent~=0.4.0
```

@tdviet can you check this?

**Comment by tdviet** [comment]
Will upgrade the requirement to 0.6.0, need some testing

**Comment by tdviet** [comment]
Fixed with https://github.com/tdviet/fedcloudclient/commit/3a13d07143a9bdc43c7545e25ea6204440a8e789
Maintaining version 1.4.1 released
